repos:
  - repo: local
    hooks:
      - id: gofmt
        name: Go formatting
        entry: gofmt -s -w
        language: system
        types: [go]
      - id: go-vet
        name: Vet maintained modules
        entry: make vet
        language: system
        pass_filenames: false
        types: [go]
