// ctx-go-src dumps Go package source in txtar format
package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"go/build"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

func main() {
	var (
		recursive = flag.Bool("r", false, "include subdirectories")
		tests     = flag.Bool("tests", false, "include test files")
	)
	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: %s [flags] <package-or-path>\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "\nDump Go package source in txtar format\n\n")
		fmt.Fprintf(os.Stderr, "Examples:\n")
		fmt.Fprintf(os.Stderr, "  %s github.com/user/pkg      # dump remote package\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "  %s ./cmd/tool               # dump local package\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "  %s -r ./pkg                 # dump directory recursively\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "\nFlags:\n")
		flag.PrintDefaults()
	}
	flag.Parse()

	if flag.NArg() != 1 {
		flag.Usage()
		os.Exit(1)
	}

	target := flag.Arg(0)

	// Find package directory
	pkgDir, err := findPackageDir(target)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error finding package: %v\n", err)
		os.Exit(1)
	}

	// Dump sources
	if err := dumpSources(pkgDir, *recursive, *tests); err != nil {
		fmt.Fprintf(os.Stderr, "Error dumping sources: %v\n", err)
		os.Exit(1)
	}
}

func findPackageDir(target string) (string, error) {
	// If it's a local path, use it directly
	if strings.HasPrefix(target, "./") || strings.HasPrefix(target, "/") {
		absPath, err := filepath.Abs(target)
		if err != nil {
			return "", err
		}
		if info, err := os.Stat(absPath); err == nil && info.IsDir() {
			return absPath, nil
		}
	}

	// Try using go list to find the package
	cmd := exec.Command("go", "list", "-f", "{{.Dir}}", target)
	output, err := cmd.Output()
	if err == nil {
		return strings.TrimSpace(string(output)), nil
	}

	// Try as a module with go mod download
	cmd = exec.Command("go", "mod", "download", "-json", target)
	output, err = cmd.Output()
	if err == nil {
		// Parse JSON output to get Dir
		// For simplicity, we'll use go list again after download
		cmd = exec.Command("go", "list", "-f", "{{.Dir}}", target)
		output, err = cmd.Output()
		if err == nil {
			return strings.TrimSpace(string(output)), nil
		}
	}

	// Try build.Import for standard library packages
	pkg, err := build.Import(target, "", build.FindOnly)
	if err == nil {
		return pkg.Dir, nil
	}

	return "", fmt.Errorf("could not find package: %s", target)
}

func dumpSources(dir string, recursive, includeTests bool) error {
	// Create header comment
	fmt.Printf("# Go source dump for %s\n", dir)
	fmt.Printf("# Generated by ctx-go-src\n\n")

	return filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		// Skip hidden directories
		if info.IsDir() && strings.HasPrefix(info.Name(), ".") && path != dir {
			return filepath.SkipDir
		}

		// Skip non-Go files
		if !strings.HasSuffix(path, ".go") {
			return nil
		}

		// Skip test files if not requested
		if !includeTests && strings.HasSuffix(path, "_test.go") {
			return nil
		}

		// Skip subdirectories if not recursive
		if !recursive && filepath.Dir(path) != dir {
			if info.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}

		// Read file
		content, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("reading %s: %w", path, err)
		}

		// Get relative path for txtar header
		relPath, err := filepath.Rel(dir, path)
		if err != nil {
			relPath = path
		}

		// Escape existing txtar headers in the content
		escapedContent := escapeTxtarHeaders(content)

		// Write txtar entry
		fmt.Printf("-- %s --\n", relPath)
		fmt.Print(string(escapedContent))
		if !bytes.HasSuffix(escapedContent, []byte("\n")) {
			fmt.Println()
		}

		return nil
	})
}

// escapeTxtarHeaders escapes lines that look like txtar headers
func escapeTxtarHeaders(content []byte) []byte {
	var result bytes.Buffer
	scanner := bufio.NewScanner(bytes.NewReader(content))

	for scanner.Scan() {
		line := scanner.Text()

		// Check if line looks like a txtar header (starts with "-- " and ends with " --")
		// This includes lines in comments like "// -- file.go --"
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "-- ") && strings.HasSuffix(trimmed, " --") &&
			strings.Count(trimmed, "--") == 2 {
			// Escape by adding a space at the beginning
			result.WriteString(" ")
		}

		result.WriteString(line)
		result.WriteByte('\n')
	}

	// Remove trailing newline if original didn't have one
	if len(content) > 0 && content[len(content)-1] != '\n' {
		result.Truncate(result.Len() - 1)
	}

	return result.Bytes()
}
